# Render.com deployment configuration
services:
  - type: web
    name: stream-relay
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    healthCheckPath: /ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
