# DigitalOcean App Platform spec
name: stream-relay
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/stream-relay
      branch: main
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3000"
